### ISSUE TITLE
Warning when installing Menlo font macOS Sierra.

### ISSUE THREAD

**Issue by nashokin** [Alhadis/Menloco#2]
![screen shot 2016-10-27 at 2 59 36 pm](https://cloud.githubusercontent.com/assets/6571738/19754094/12c86da0-9c56-11e6-944a-e52c68164677.png)

**Comment by Alhadis** [comment]
@nashokin What happened?

**Comment by nashokin** [comment]
One is a system font, but different extension. Nothing wrong with the compiled font, works perfectly, didn't think it was an issue anymore.[cid:6e6ab630-36e5-4610-87b3-a1426e9f2f3a]

Sent from Outlookhttp://aka.ms/weboutlook

**Comment by Alhadis** [comment]
Ah good, glad to hear it! Thanks!
